services:
  db:
    image: postgres:17-alpine
    container_name: medfind-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: idoctor_db
      POSTGRES_USER: abduqodir
      POSTGRES_PASSWORD: medfind_local_dev_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abduqodir -d idoctor_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
